cors:
  originsPatterns: "http://localhost:8080,http://localhost:3000"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api_restful?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
    open-in-view: true
springdoc:
  pathsToMatch: /**/**
  swagger-ui:
    use-root-path: true